version: '3'
services:
    app:
        build: ./api
        ports:
            - "8181:8181"
        environment:
            PG_URL:  postgres://${PG_USER}:${PG_PASSWORD}@postgres:5432/postgres
            LISTEN_PORT: :8181
        restart: always

    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_USER: ${PG_USER}
        ports:
            - 5432:5432
        volumes:
            - app-storage:/var/lib/postgresql/data

    auth:
        build: ./auth
        ports:
            - "8182:8182"
        environment:
            LISTEN_PORT: :8182
        restart: always

    redis:
        image: redis
        # network_mode: host
        ports:
            - 6389:6389
        volumes:
            - auth-storage:/var/lib/redis
        restart: always
volumes:
    app-storage:
    auth-storage:
