version: '3'
services:
    app:
        build: ./api
        ports:
            - "8181:8181"
        environment:
            PG_PASS: somepassword
            PG_URL:  postgres://${PG_USER}:${PG_PASSWORD}@postgres:5432/postgres
            LISTEN_PORT: :8181
        restart: always

    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_USER: ${PG_USER}
        ports:
            - 5432:5432
        volumes:
            - db-storage:/var/lib/postgresql/data
volumes:
    db-storage:
