version: '3'
services:
    app:
        build: ./api
        ports:
            - "8181:8181"
        depends_on:
            - postgres
        environment:
            PG_URL:  postgres://${PG_USER}:${PG_PASSWORD}@postgres:5432/postgres
            LISTEN_PORT: :8181
        restart: always

    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_USER: ${PG_USER}
        ports:
            - 5432:5432
        volumes:
            - app-storage:/var/lib/postgresql/data

    auth:
        build: ./auth
        ports:
            - "8182:8182"
        depends_on:
            - redis
        env_file:
            - ./auth/.env
        environment:
            LISTEN_PORT: :8182
            REDIS_ADDR: redis:6379
        restart: always

    redis:
        image: redis
        ports:
            - 6379:6379
        volumes:
            - auth-storage:/var/lib/redis
        restart: always

    notifications:
        build: ./notifications
        environment:
            AMQP_ADDR: "amqp://guest:guest@rabbitmq:5672"
        env_file:
            - ./notifications/.env
        depends_on: 
            - rabbitmq
        restart: always

    rabbitmq:
        image: rabbitmq
        ports:
            - "5672:5672"
        volumes:
            - notifications-storage:/var/lib/rabbitmq
        restart: always

volumes:
    app-storage:
    auth-storage:
    notifications-storage:
